spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Urosalud
    username: root
    password: Osoted12.
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  server:
    port: 8080